name: Run validation on action

on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/container-app-sample-AutoDeployTrigger-f9592e1e-9d15-4236-90db-8a0f848e3493.yml'

  # Allow mannually trigger 
  workflow_dispatch:
jobs: 
  test:
    runs-on: ubuntu-latest
    steps: 
      - name : Log in to Azure
        uses: azure/login@v1
        with: 
          creds: ${{ secrets.AZURE_CREDENTIALs }}  
      - name: Build and deploy Container App
        uses: azure/container-apps-deploy-action@v0
        with:
          appSourcePath: '${{ github.workspace }}/oryx/tests/SampleApps/DotNetCore/NetCore6PreviewWebApp'
          acrName: ${{ vars.TEST_ACR_NAME }}
          acrUsername: ${{ secrets.TEST_REGISTRY_USERNAME }}
          acrPassword: ${{ secrets.TEST_REGISTRY_PASSWORD }}
          containerAppName: ${{ env.TEST_CONTAINER_APP_NAME }}
          containerAppEnvironment: ${{ vars.TEST_EXISTING_CONTAINER_APP_ENV }}
          resourceGroup: ${{ vars.TEST_RESOURCE_GROUP_NAME }}
          imageToBuild: ${{ env.TEST_FULL_ACR_NAME }}/${{ env.TEST_IMAGE_REPOSITORY }}:${{ env.TEST_IMAGE_TAG }}
          disableTelemetry: ${{ vars.TEST_DISABLE_TELEMETRY }}
